# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  if Vagrant.has_plugin? "vagrant-vbguest"
  config.vbguest.no_install = true
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true
  end
  config.vm.define :machine2 do |machine2|
  machine2.vm.box = "bento/ubuntu-20.04"
  machine2.vm.network :private_network, ip: "192.168.100.2"
  machine2.vm.hostname = "machine2"
  end
  config.vm.define :machine1 do |machine1|
  machine1.vm.box = "bento/ubuntu-20.04"
  machine1.vm.network :private_network, ip: "192.168.100.3"
  machine1.vm.hostname = "machine1"
  end
end
