# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

config.vm.define :machine1 do |machine1|
  machine1.vm.box = "bento/ubuntu-20.04"
    machine1.vm.network :private_network, ip: "192.168.100.3"
    machine1.vm.hostname = "machine1"
  end
end
