# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL']='yes'

Vagrant.configure("2") do |config|
  NodeCount = 3

    (1..NodeCount).each do |i|
      config.vm.define :"ubuntuvm0#{i}" do |node|
        node.vm.box = "bento/ubuntu-20.04"
        node.vm.network :private_network, ip: "192.168.100.10#{i}"
        node.vm.hostname = "ubuntuvm0#{i}"
      end
    end
end
